//
//  Resolver.swift
//  Generated by dikitgen.
//

import Action
import DIKit
import Foundation
import Logger
import RxSwift

extension DomainResolver {

    func resolveAuthorizationUseCaseImpl(health: HealthKitType) -> AuthorizationUseCaseImpl {
        return AuthorizationUseCaseImpl(dependency: .init(health: health))
    }

    func resolveDomainResolver() -> DomainResolver {
        return provideResolver()
    }

    func resolveHomeTimelineCaseImpl(health: HealthKitType) -> HomeTimelineCaseImpl {
        return HomeTimelineCaseImpl(dependency: .init(health: health))
    }

}

