//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Domain
import Environments
import Foundation
import Infrastructure
import RxCocoa
import RxSwift
import UIKit

extension AppResolver {

    func resolveAppResolver() -> AppResolver {
        return provideResolver()
    }

    func resolveHomeNavigatorImpl(navigationController: UINavigationController) -> HomeNavigatorImpl {
        let appResolver = resolveAppResolver()
        return HomeNavigatorImpl(dependency: .init(resolver: appResolver, navigationController: navigationController))
    }

    func resolveHomeViewController(navigator: HomeNavigator, authorizationUseCase: AuthorizationUseCase, homeTimelineUseCase: HomeTimelineUseCase) -> HomeViewController {
        let homeViewModel = resolveHomeViewModel(navigator: navigator, authorizationUseCase: authorizationUseCase, homeTimelineUseCase: homeTimelineUseCase)
        return HomeViewController.makeInstance(dependency: .init(viewModel: homeViewModel))
    }

    func resolveHomeViewModel(navigator: HomeNavigator, authorizationUseCase: AuthorizationUseCase, homeTimelineUseCase: HomeTimelineUseCase) -> HomeViewModel {
        return HomeViewModel(dependency: .init(navigator: navigator, authorizationUseCase: authorizationUseCase, homeTimelineUseCase: homeTimelineUseCase))
    }

    func resolveLaunchScreenNavigatorImpl(window: UIWindow?) -> LaunchScreenNavigatorImpl {
        let appResolver = resolveAppResolver()
        return LaunchScreenNavigatorImpl(dependency: .init(resolver: appResolver, window: window))
    }

    func resolveLaunchScreenViewController(navigator: LaunchScreenNavigator) -> LaunchScreenViewController {
        let launchScreenViewModel = resolveLaunchScreenViewModel(navigator: navigator)
        return LaunchScreenViewController.makeInstance(dependency: .init(viewModel: launchScreenViewModel))
    }

    func resolveLaunchScreenViewModel(navigator: LaunchScreenNavigator) -> LaunchScreenViewModel {
        return LaunchScreenViewModel(dependency: .init(navigator: navigator))
    }

    func resolveUseCase() -> UseCase {
        return provideUseCase()
    }

}

